import type { Metadata } from 'next';
import { Playfair_Display, Lora, Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const playfair = Playfair_Display({ variable: '--font-serif', subsets: ['latin'] });
const inter = Lora({ variable: '--font-sans', subsets: ['latin'] });
const lora = Lora({ variable: '--font-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <body>{children}</body>
    </html>
  );
}
